In [60]:
import bokeh as bk
import bokeh.models as models
import bokeh.plotting
from bokeh.plotting import figure, show
import pandas as pd
#import polars as pl
import numpy as np
import geopandas as gpd
from pathlib import Path
import figs as f
from collections import namedtuple
from figs.figure_transforms import ScalableFigure
from figs._aq_test import AquiferTestFigure
import plotly.graph_objs as go
from simple_modflow.modflow.utils import read_gpkg
import shapely as shp

In [58]:
f6path = Path(r"C:\Users\lukem\QGIS\SHP\lakepointe\facility 6 layouts.gpkg")
fillpath = Path(r"C:\Users\lukem\QGIS\SHP\lakepointe\lakepointe fill polys.gpkg")
f6 = read_gpkg(fillpath, crs='EPSG:2926').to_crs('EPSG:2927')
f6 = f6.iloc[0].geometry
pt = f6.representative_point()
pt = [pt.x, pt.y]
pt

Imported 2 features from C:\Users\lukem\QGIS\SHP\lakepointe\lakepointe fill polys.gpkg


[1248833.316900771, 748480.6543691203]

In [87]:
fill_areas = Path(r"C:\Users\lukem\QGIS\SHP\lakepointe\fill north of facility 6 reprojected.gpkg")
fill_areas = read_gpkg(fill_areas)
fill = fill_areas.geometry.iloc[0].geoms[0]
type(fill)

Imported 1 features from C:\Users\lukem\QGIS\SHP\lakepointe\fill north of facility 6 reprojected.gpkg


AttributeError: 'Series' object has no attribute 'geoms'

In [74]:
fill_areas = Path(r"C:\Users\lukem\QGIS\SHP\lakepointe\lakepointe fill polys.gpkg")
fill_areas = read_gpkg(fill_areas)
fill_areas = fill_areas.iloc[0]

Imported 2 features from C:\Users\lukem\QGIS\SHP\lakepointe\lakepointe fill polys.gpkg


In [20]:
fig = AquiferTestFigure()
fig.x_scale = 1
fig.y_scale = 1
"""fig._plot_width = 72*11
fig._plot_height = 72*8.5"""
fig._dots_per_base_unit = 96 * (59/32)
fig.plot_width = 5.966101694915254
fig.plot_height = 4.610169491525424

In [21]:
eb110 = Path(r"C:\Users\lukem\Python\data\110W 72hr.xlsx")
df = pd.read_excel(eb110)

In [68]:
def read_gpkg(filepath: Path, crs="EPSG:2927"):
    
    layer=True
    layer_num = 0
    layers = []
    while layer:
        try:
            geometry = gpd.read_file(filepath, layer=layer_num)
            layers.append(geometry.geometry[0])
            layer_num += 1
        except:
            layer = False
            print(f'Imported {layer_num} features from {filepath}')
    gdf = gpd.GeoDataFrame(geometry=layers, crs=crs)
    return gdf

read_gpkg(Path(r"C:\Users\lukem\QGIS\SHP\lakepointe\facility 6 layouts.gpkg"))

Imported 1 features from C:\Users\lukem\QGIS\SHP\lakepointe\facility 6 layouts.gpkg


geometry
0  POLYGON ((1248913.375 748361.93, 1248916.146 7...

Empty GeoDataFrame
Columns: []
Index: []

In [24]:
fig.write_scaled_pdf(pdf_renderer='cairo')

writing SVG to temp_plot.svg
writing SVG to temp_plot.svg
using cairo


In [22]:
cols = []
for i, col in enumerate(df.columns):
    if 'time' in col:
        fig.add_scattergl(
            x=df.iloc[:,i],
            y=df.iloc[:, i+1],
            name=df.columns[i+1]
        )

In [28]:
fig.write_html('EB110.html', config={'scrollZoom': True})

In [50]:
const_rates = aq.filter(like='Hr')
for i, col in enumerate(const_rates.columns):
    if i%2 == 0:
        fig.add_scattergl(
            x=const_rates.iloc[:, i],
            y=const_rates.iloc[:, i+1], 
            name=str(col),
        )
fig.show()

In [6]:
fig.write_svg()

writing SVG to temp_plot.svg


<module 'svglib' from 'C:\\Users\\lukem\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\svglib\\__init__.py'>

In [4]:
import numpy as np

a = np.array([[1],
              [2],
              [3],
              [4]])  # Shape (4, 1)

b = np.array([1, 2, 3, 4, 5])  # Shape (1, 5)

# Using np.broadcast_arrays()
a_broadcasted, b_broadcasted = np.broadcast_arrays(a, b)

print("Broadcasted 'a':\n", a_broadcasted)
print("Broadcasted 'b':\n", b_broadcasted)


Broadcasted 'a':
 [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
Broadcasted 'b':
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [2]:
df = pd.DataFrame()
df['x'] = [1,2,3,4,5]
df['y'] = [5,4,3,2,1]

In [3]:
source = models.sources.ColumnDataSource(df)

In [4]:
fig = figure()
fig.scatter(source=source)

GlyphRenderer(id='p1038', ...)

In [29]:
show(fig)

In [7]:
pl.DataFrame(df)

shape: (5, 2)
┌─────┬─────┐
│ x   ┆ y   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 5   │
│ 2   ┆ 4   │
│ 3   ┆ 3   │
│ 4   ┆ 2   │
│ 5   ┆ 1   │
└─────┴─────┘

In [4]:
x_length_grid_in_inches

16.125

In [18]:
from pathlib import Path
import pandas as pd
path = Path().home() / 'Python/data/tehaleh_wls.xlsx'
dfdd = pd.read_excel(path, sheet_name='WellDD').set_index('Date Time').apply(lambda col: pd.to_numeric(col, errors='coerce'))
dfdd.index.to_list()

WellHD


[Timestamp('1996-01-01 12:00:00'),
 Timestamp('1996-01-02 12:00:00'),
 Timestamp('1996-01-03 12:00:00'),
 Timestamp('1996-01-04 12:00:00'),
 Timestamp('1996-01-05 12:00:00'),
 Timestamp('1996-01-06 12:00:00'),
 Timestamp('1996-01-07 12:00:00'),
 Timestamp('1996-01-08 12:00:00'),
 Timestamp('1996-01-09 12:00:00'),
 Timestamp('1996-01-10 12:00:00'),
 Timestamp('1996-01-11 12:00:00'),
 Timestamp('1996-01-12 12:00:00'),
 Timestamp('1996-01-13 12:00:00'),
 Timestamp('1996-01-14 12:00:00'),
 Timestamp('1996-01-15 12:00:00'),
 Timestamp('1996-01-16 12:00:00'),
 Timestamp('1996-01-17 12:00:00'),
 Timestamp('1996-01-18 12:00:00'),
 Timestamp('1996-01-19 12:00:00'),
 Timestamp('1996-01-20 12:00:00'),
 Timestamp('1996-01-21 12:00:00'),
 Timestamp('1996-01-22 12:00:00'),
 Timestamp('1996-01-23 12:00:00'),
 Timestamp('1996-01-24 12:00:00'),
 Timestamp('1996-01-25 12:00:00'),
 Timestamp('1996-01-26 12:00:00'),
 Timestamp('1996-01-27 12:00:00'),
 Timestamp('1996-01-28 12:00:00'),
 Timestamp('1996-01-

In [20]:
import pandas as pd
from pathlib import Path
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource
path = Path().home() / 'Python/data/tehaleh_wls.xlsx'
df_dd = pd.read_excel(path, sheet_name='WellDD').set_index('Date Time').apply(
    lambda column: pd.to_numeric(column, errors='coerce'))
df_dd = df_dd.drop(['Month', 'Year', 'Water Year'], axis='columns')
df_hd = pd.read_excel(path, sheet_name='WellHD').set_index('Date').apply(
    lambda column: pd.to_numeric(column, errors='coerce'))


WellHD
WellHD


In [1]:
from _fig import Fig
import figs
import plotly.graph_objs as go
from pathlib import Path
import plotly.io as pio
fig = Fig()
import pandas as pd
import geopandas as gpd
import shapely as shp
shp_path = Path.home() / 'Python/data/explo/AESI_Explorations.shp'
wls_df = pd.read_excel(Path.home() / 'Python/data/Tehaleh_wls.xlsx', sheet_name='WellDD').set_index('Date Time')
pointshp = gpd.read_file(shp_path)
pointshp = pointshp.to_crs(4326)
wells_shp = pointshp[pointshp['ExploType']=='MW, EB-1W, TW, OBW']
wls_df = pd.read_excel(Path.home() / 'Python/data/Tehaleh_wls.xlsx', sheet_name='WellDD')

WellHD


In [7]:
map_fig = Fig()
y = wells_shp.geometry.y
x = wells_shp.geometry.x
map_center = {
    'lat': list(wells_shp.unary_union.centroid.coords)[0][1],
    'lon': list(wells_shp.unary_union.centroid.coords)[0][0]
}
wells_hover = {
    'Name': wells_shp['ExploName'].tolist(),
    'Proj #': wells_shp['AESI_ProjN'].tolist(),
    'Proj Name': wells_shp['AESI_Pro_2'].tolist()
}
custom_data, hover_template = figs.create_hover(wells_hover)
map_fig.add_scattermapbox(lat=y, lon=x, customdata=custom_data, hovertemplate=hover_template, marker_color='black',
                          text=wells_shp['ExploName'].tolist())
map_fig.update_layout(
    mapbox_style="open-street-map",
    mapbox_center=map_center,
    mapbox_zoom=7
)
map_fig.show()
map_fig.write_json('fig.json')

In [5]:
wells_shp 

id AESI_ProjN AESI_Pro_1                     AESI_Pro_2 Phase  \
23        24.0   20130422     130422              Perrinville Creek   KHA   
54        55.0   20130211     130211                       Delridge   NaN   
55        56.0   20130211     130211                       Delridge   NaN   
108      109.0   20130323     130323             Holy Family Parish   NaN   
111      112.0   20110220     110220                   Barton Basin   KHA   
...        ...        ...        ...                            ...   ...   
20742  20743.0   20160066     160066  Well Installation and Testing   EHA   
20743  20744.0   20160066     160066  Well Installation and Testing  E003   
20787  20788.0   20120528     120528      New Wilson Pacific School   KEA   
20803  20804.0   20150005     150005                        Park 77   EEA   
20804  20805.0   20150005     150005                        Park 77   EEA   

                ExploType       ExploType_  ExploName  ExploDepth  \
23     MW, EB-1W, TW, OBW  MONITORING WELL       MW-1        87.0   
54     MW, EB-1W, TW, OBW  MONITORING WELL       MW-1         NaN   
55     MW, EB-1W, TW, OBW  MONITORING WELL       MW-2         NaN   
108    MW, EB-1W, TW, OBW  MONITORING WELL       MW-1         NaN   
111    MW, EB-1W, TW, OBW  MONITORING WELL      MW-19        65.8   
...                   ...              ...        ...         ...   
20742  MW, EB-1W, TW, OBW  MONITORING WELL       EW-2       423.0   
20743  MW, EB-1W, TW, OBW  MONITORING WELL       EW-3       600.0   
20787  MW, EB-1W, TW, OBW  MONITORING WELL  EB-9/MW-1        15.8   
20803  MW, EB-1W, TW, OBW  MONITORING WELL       MW-1        36.0   
20804  MW, EB-1W, TW, OBW  MONITORING WELL       MW-2        36.5   

                     ExploDate  ...  Radiocarbo Editor    Editor_res  \
23     2014/05/02 16:00:00.000  ...         NaN    KLB    Karen Behm   
54                         NaN  ...         NaN    KLB    Karen Behm   
55                         NaN  ...         NaN    KLB    Karen Behm   
108                        NaN  ...         NaN    KLB    Karen Behm   
111    2011/10/19 16:00:00.000  ...         NaN    KLB    Karen Behm   
...                        ...  ...         ...    ...           ...   
20742  2016/12/02 00:00:00.000  ...         Yes    MPT  Michael Trop   
20743  2017/08/03 00:00:00.000  ...         Yes    MPT  Michael Trop   
20787  2013/02/01 00:00:00.000  ...         NaN    MPT  Michael Trop   
20803  2015/09/21 00:00:00.000  ...         Yes    MPT  Michael Trop   
20804  2015/09/21 00:00:00.000  ...         Yes    MPT  Michael Trop   

                      EditDate               CreationDa     Creator  \
23     2018/03/08 16:00:00.000  2023/01/31 16:59:15.279  nfink_AESI   
54     2018/03/08 16:00:00.000  2023/01/31 16:59:15.279  nfink_AESI   
55     2018/03/08 16:00:00.000  2023/01/31 16:59:15.279  nfink_AESI   
108    2018/03/08 16:00:00.000  2023/01/31 16:59:15.279  nfink_AESI   
111    2019/11/05 16:00:00.000  2023/01/31 16:59:15.279  nfink_AESI   
...                        ...                      ...         ...   
20742  2024/02/26 00:00:00.000  2024/02/26 17:36:44.746  mtrop_aesi   
20743  2024/02/26 00:00:00.000  2024/02/26 17:58:14.244  mtrop_aesi   
20787  2024/02/26 00:00:00.000  2024/02/26 22:43:58.530  mtrop_aesi   
20803  2024/02/26 00:00:00.000  2024/02/26 23:43:08.168  mtrop_aesi   
20804  2024/02/26 00:00:00.000  2024/02/26 23:43:13.536  mtrop_aesi   

                    EditDate_1    Editor_1  wq                     geometry  
23     2023/01/31 16:59:15.279  nfink_AESI NaN  POINT (-122.34167 47.83094)  
54     2023/01/31 16:59:15.279  nfink_AESI NaN  POINT (-122.35606 47.53183)  
55     2023/01/31 16:59:15.279  nfink_AESI NaN  POINT (-122.35652 47.52569)  
108    2023/01/31 16:59:15.279  nfink_AESI NaN  POINT (-122.35899 47.51653)  
111    2023/01/31 16:59:15.279  nfink_AESI NaN  POINT (-122.37278 47.53186)  
...                        ...         ...  ..                          

In [3]:
f = Fig()
f.show()

In [5]:
import plotly
import itertools
cycle = itertools.cycle(plotly.colors.DEFAULT_PLOTLY_COLORS)
next(cycle)

'rgb(31, 119, 180)'